version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"
    command: redis-server --requirepass abc1234
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:abc1234
    depends_on:
      - redis